[package]
name = "legend"
version = "0.1.0"
authors = ["Zelda Hessler <zelda.hessler@gmail.com>"]

[features]
cargo-resource-root = []

[dependencies]
ggez = "0.4"
rand = "0.4"
shrev = "0.8"
log = "0.4"
fern = { version = "0.5", features = ["colored"] }
